
$(document).ready(function(){
  
    $('#btn3').click(function(){
        $("div").slideToggle();
        
    });
    $(document).ready(function(){
  
        $('.btn9').click(function(){
            $(".k").slideToggle();
            
        });
       
    
    });
    $(document).ready(function(){
  
        $('.btn6').click(function(){
            $(".y").slideToggle();
            
        });
       
    
    });
    
    


    $(document).ready(function(){
  
        $('.btn9').click(function(){
            $(".h").slideToggle();
            
        });
       
    
    });$(document).ready(function(){
      
        $('.btn8').click(function(){
            $(".n").slideToggle();
            
        });
       
    
    });
    

});
$('.btn1').click(function(){
    $(".a").slideToggle();
    $(".a").animate({'width':200});
    $(".a").animate({'left':100});
    $(".a").animate({'height':300});
    $(".a").animate({'opacity':0.2}); 
    $(".a").animate({
        left:'500px',
    });
        